# Generated by Django 5.0.6 on 2024-06-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('foundation', '0002_rename_status_statuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foundation.stage'),
        ),
        migrations.AddField(
            model_name='task',
            name='statuss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foundation.statuss'),
        ),
    ]
