# Generated by Django 5.0.6 on 2024-06-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_core', '0001_initial'),
        ('core', '0002_task_stage_task_statuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_core.dept'),
        ),
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_core.role'),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client_core.user'),
        ),
    ]
